version: '3.8'

services:
  mariadb:
    image: mariadb
    build: /home/onaciri_42/Inception/srcs/requirements/mariadb/.
    container_name: mariadb
    restart: always
    env_file:
     - .env
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - inception_net

  wordpress:
    container_name: wordpress
    build: /home/onaciri_42/Inception/srcs/requirements/wordpress/.
    restart: always
    env_file:
     - .env
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - mariadb
    networks:
      - inception_net
    expose:
      - 9000
    image: wordpress

  nginx:
    container_name: nginx
    build: /home/onaciri_42/Inception/srcs/requirements/nginx/.
    restart: always
    env_file:
     - .env
    volumes:
      - wordpress:/var/www/html/
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception_net
    image: nginx

networks:
  inception_net:
    name: inception_net

volumes:
  wordpress:
    driver : local
    driver_opts :
      o : bind
      device : /home/onaciri/data/wordpress
      type: none

  mariadb:
    driver : local
    driver_opts :
      o : bind
      device : /home/onaciri/data/mariadb
      type: none
    